### ISSUE TITLE
Feature request: re-import all blocks

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion#560]
# Introduction
`reindex`, to rebuild the database by re-importing all existing blocks, is a useful feature. It allows node operators to quickly clean up the database without doing a sync with the network; it also enables developers to verify if their changes will break any consensus rule.

# Current situation
This feature is missing in the current Aion implementation.

# Task Description
We're asking for contributors to implement this feature for https://github.com/aionnetwork/aion. This task can be divided into the following steps:
- Extract all blocks from the current database folders;
- Wipe the whole database (or move to another temporary place);
- Rebuild the index and state by importing all the extracted blocks;
- Verify if the whole process is successful or not;
- Expose this feature by extending the currently command line interface.

Note: we're open to alternative approaches.

# Acceptance Criteria
- The code implements the targets described above
- The code is well documented and fully covered by unit tests
- The code is compliant with Aion's code convention
- The code gets merged into the main code repository

# Required Skill
Participants needs to have experience in Java software development, and have basic knowledge about blockchain system.

# Guidance
Technical support is available through [Gitter](https://gitter.im/aionnetwork/Lobby).

**Comment by qoire** [comment]
@kzeine, this is a good candidate for bounty

**Comment by AlexandraRoatis** [comment]
Most of this functionality is already implemented between the `./aion.sh -r` and `./aion.sh --state FULL/SPREAD/TOP`.

**Comment by AlexandraRoatis** [comment]
PR #800 introduces a new CLI command `--redo-import` / `--redo-import <height>`.
This command triggers a process of reimporting all the blocks from the given height (or from the genesis block when no parameter is provided). The` state`, `details`, `storage` and `transaction` databases are completely wiped and rebuilt when starting from the genesis block. The `index` database is expected to have the correct main chain blocks information for this task to complete.

Future enhancements:
- [ ] fully rebuild the `index` database as well;
- [ ] improve time estimates by approximating and factoring in the number of keys added to the state;
- [ ] improve execution speed by batching IO operations;
- [ ] improve code by using `nanoTime` and `TimeUnit`.
