### ISSUE TITLE
Expand Sync Statistics

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#661]
# Introduction
We are looking to expand the sync statistics for the Aion Kernel to produce a more comprehensive set that helps users and developers better monitor the Kernel.
# Current situation
The feature set described below is missing from the current Aion implementation.
# Task Description
We're asking for contributors to modify the class [`SyncStats.java`](https://github.com/aionnetwork/aion/blob/master-pre-merge/modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java) to expand the sync statistics gathered and printed in the logs.
The functionality to be added is:
* The **percentage of requests** made to each peer with respect to the total number of requests made.
* A list of peers ordered by the **total number of blocks received** from each peer used to determine who is providing the majority of blocks, i.e. top seeds.
* A list of peers ordered by the **total number of blocks requested** by each peer used to determine who is requesting the majority of blocks, i.e. top leeches.
* **Average response time** between sending blocks out and that peer responding shown for each peer and averaged for all peers.
* **Unit tests** showing correct functionality and full coverage of the methods added to SyncStats class to provide the above-mentioned functionality additions.
# Acceptance Criteria
- The code implements the targets described above.
- The code is well documented and fully covered by unit tests.
- The code is compliant with Aion's [code conventions](https://github.com/aionnetwork/aion/wiki/Aion-Code-Conventions).
- The code gets merged into the main code repository.
# Required Skill
Participants need to have experience in Java software development, debugging and have basic knowledge about blockchain systems.
# Guidance
Details regarding this issue can be requested in comments.
Further technical support is available through [Gitter](https://gitter.im/aionnetwork/Lobby).

**Comment by AlexandraRoatis** [comment]
@santteegt you are right, some deep debugging will be needed to complete the task. You should be able to import the project using Gradle in your IDE of choice. Changes must be based on the [`master-pre-merge`](https://github.com/aionnetwork/aion/tree/master-pre-merge) branch. The data for the statistics will be collected from [`TaskImportBlocks.java`](https://github.com/aionnetwork/aion/blob/master-pre-merge/modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java) and the information should be printed in [`TaskShowStatus.java`](https://github.com/aionnetwork/aion/blob/master-pre-merge/modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java) under debug logging. Both classes already reference a common `SyncStats` object.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 months, 4 weeks from now.
Please review their action plans below:


**1) [santteegt](https://gitcoin.co/profile/santteegt) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/aionnetwork/aion/661/1353?mutate_worker_action=approve&worker=santteegt) | [reject worker](https://gitcoin.co/issue/aionnetwork/aion/661/1353?mutate_worker_action=reject&worker=santteegt))_.**

I have almost 10 year of Java programming experience. Looks like an easy task, however I would like to know some background on where and how to fetch necessary data to genererate those stats, as well as a little roadmap on when the SyncStats.java is executed by a running node (I could do some deep debugging tasks to find out)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aionnetwork/aion/661/1353).


**2) [KevinKelley](https://gitcoin.co/profile/KevinKelley) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/aionnetwork/aion/661/1353?mutate_worker_action=approve&worker=KevinKelley) | [reject worker](https://gitcoin.co/issue/aionnetwork/aion/661/1353?mutate_worker_action=reject&worker=KevinKelley))_.**

I'm interested to work on this, if it's not already assigned.  I've got plenty of Java experience; some blockchain too. Still new to Aion, but I'd like to get involved.

Looking at the code, I'm thinking that SyncStats will need to maintain a map of per-peer statistics: counts of requests to the peer, receipts from peer, running-average response time per request.  TaskImportBlocks will update this map (in processBatch) and taskShowStatus will dump it...

Not sure whether PeerState Mode should affect these stats?  I assume not, stats would be accumulated regardless of forward/backward/etc.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aionnetwork/aion/661/1353).

**Comment by gitcoinbot** [comment]
@santteegt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=1) | [3 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=3) | [5 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=5) | [10 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=10) | [100 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=100)

**Comment by santteegt** [comment]
Hi,

Thanks for accepting my request. I'll be start working in this bounty as soon as possible

**Comment by gitcoinbot** [comment]
@santteegt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=1) | [3 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=3) | [5 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=5) | [10 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=10) | [100 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=100)

**Comment by gitcoinbot** [comment]
@santteegt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=1) | [3 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=3) | [5 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=5) | [10 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=10) | [100 days](https://gitcoin.co/issue/aionnetwork/aion/661/1353?snooze=100)

**Comment by santteegt** [comment]
Hi,

I had a couple of issues when setting up a development environment, as I work with Mac OS, but I just solved. I already made some initial debugging to enable the `TaskShowStatus.java` process, and now I'm ready to work on the stats generation. I'll be giving you more updates in the following days.

**Comment by karysta6** [comment]
@santteegt Thanks for the update!

**Comment by AlexandraRoatis** [comment]
@santteegt Thanks for the update!

**Comment by santteegt** [comment]
Hi,

During debugging I realize that the node is always getting the following output on every block it tries to process:

```
<import-mode-before: node = c33d22, sync mode = BACKWARD, base = 1>
<import-status: node = c33d22, sync mode = BACKWARD, hash = 28375c, number = 1, txs = 0, result = NO_PARENT, time elapsed = 0 ms>
Stopped importing batch due to NO_PARENT result. Stored 0 out of 24 blocks starting at hash = 28375c, number = 1 from node = c33d22.
<import-mode-after: node = c33d22, sync mode = BACKWARD, base = 1>
```

What could be the problem? This is the [config.xml](https://pastebin.com/KyqJfJSV) the node uses (default config file), and It is connecting to the mainnet. Is there a specific configuration to use a testnet for this issue purposes?

**Comment by AlexandraRoatis** [comment]
It looks like your current configuration doesn't match the genesis file.

**Comment by santteegt** [comment]
hi,

I just wanted to let you know that I'm currently in progress to finish this bounty. If you want, you can take a look at the commit logs on my fork repo https://github.com/santteegt/aion/commits/master-pre-merge. I have already covered the first two statistics from the task description. I'll try to finish the rest during the weekend

**Comment by AlexandraRoatis** [comment]
Sounds good. We will review the code when you submit the PR.

**Comment by santteegt** [comment]
Hi,

I have a question regarding the **total number of blocks requested by leechers** and their **average response time** for receiving a block. Digging into the code, it looks like the `BlockPropagationHandler` is in charge to send a new block to all peers with lower blockNumbers. Here, an instance of the `P2pMgr.java` queues the new block in the `sendMsgQue`, while within it, the `TaskSend` thread process each message in the queue through a `TaskWrite` thread.

The `TaskWrite.java` class also hold an instance of the `P2pMgr`, so my question is: is it correct to collect the corresponding statistics from within this class?. To do so, the `P2pMgr` needs an instance of the `SyncStats` class in order to be able to update statistics for leechers, which can be added during initialization (under the `initializeHub` method in `AionHub.java`).

Let me know what you think about this approach.

**Comment by AlexandraRoatis** [comment]
* For the leeches statistics look at the classes `ReqBlocksHeadersHandler` and `ReqBlocksBodiesHandler`. You will need to give access to the statistics from the p2p manager or from those classes. Also, you can divide the statistics to count headers and bodies separately or just count the block bodies.

* I now noticed that the average response time description actually has a typo in it; it's supposed to be:
_Average response time between sending **requests** out and that peer responding shown for each peer and averaged for all peers._ 
Because tracking all request types may be very complicated this can be limited to status requests, which are implemneted in the classes `TaskGetStatus` and `ResStatusHandler`.

**Comment by santteegt** [comment]
Thanks for your insights. I've finished developing all four stats you required. Changes have been pushed in my fork for the moment, once I cover the necessary unit tests, I'll create a PR for revision.

**Comment by santteegt** [comment]
I also wanted to attach screenshots on how stats are currently being visualized in the logs so you can give me any feedback on how you want to get them to be outlined on the screen.

* The percentage of requests made to each peer with respect to the total number of requests made.

![screen shot 2018-11-02 at 1 29 53 am](https://user-images.githubusercontent.com/926341/47897716-d81f4000-de40-11e8-8d11-19f20db07158.png)

* A list of peers ordered by the total number of blocks received from each peer

![screen shot 2018-11-02 at 1 30 56 am](https://user-images.githubusercontent.com/926341/47897742-ef5e2d80-de40-11e8-95bf-b6d0d2aa115f.png)

* A list of peers ordered by the total number of blocks requested by each peer

![screen shot 2018-11-02 at 1 30 34 am](https://user-images.githubusercontent.com/926341/47897762-fbe28600-de40-11e8-9c3a-fe889bb38ebf.png)

* Average response time between sending requests out and that peer responding shown for each peer and averaged for all peers

![screen shot 2018-11-02 at 1 31 16 am](https://user-images.githubusercontent.com/926341/47897785-0dc42900-de41-11e8-831a-94f6e2d72fd0.png)

**Comment by AlexandraRoatis** [comment]
Thank you for the work and the screenshots. I have a few comments below:

- For the percentage of requests (first image), it would be nice to see the peers ordered by the percentage with the highest percentages on top. 
- The second image looks good. I'm wondering why some peers have 0 blocks though. Is it because it lists all peers and some have not sent any blocks yet, or are duplicate blocks (sent by multiple peers) ignored? If it's the first case, it's not necessary to list the peers with 0 sent blocks. If it's the second, I think duplicate blocks should be counted as well. So the received blocks should be added to the statistics before filtering out the ones already imported.
- I think there's a small bug in the third image because it prints percentages instead of the total number of blocks.
- The fourth image looks good. A nice addition would be to see the peers ordered by the response time with the lowest times on top.

Since you are about to create the PR, I want to add a small reminder about rebasing your branch on the latest changes from the `master-pre-merge` branch. Opting for rebase over merge is a new practice we have been applying to keep the change history as linear as possible and to handle merge conflicts in the commits with the new feature instead of having them as separate merge commits.

**Comment by santteegt** [comment]
Hi,

Thanks for your comments. I have updated each requirement as follows

* *The percentage of requests made to each peer with respect to the total number of requests made*: peers are now ordered by their percentage with the highest percentages on top.

![screen shot 2018-11-03 at 1 32 59 am](https://user-images.githubusercontent.com/926341/47960382-bbae0f80-dfc8-11e8-9d3c-65bc3542f4cc.png)

* *A list of peers ordered by the total number of blocks received from each peer*: you're right, I was omitting duplicate blocks. Now, those are taken into account, which also removed the listing of peers with zero imported blocks.

![screen shot 2018-11-03 at 1 33 15 am](https://user-images.githubusercontent.com/926341/47960383-c49ee100-dfc8-11e8-9cd1-93951363d57a.png)

* *A list of peers ordered by the total number of blocks requested by each peer*: the list now does present total No. of requested blocks instead of percentages.

![screen shot 2018-11-03 at 1 33 37 am](https://user-images.githubusercontent.com/926341/47960384-ce284900-dfc8-11e8-91a3-effcfe7cd640.png)

* *Average response time between sending requests out and that peer responding shown for each peer and averaged for all peers*: peers are now ordered by their average response time with the lowest times on top. The overall averaged response time is shown first.

![screen shot 2018-11-03 at 1 33 58 am](https://user-images.githubusercontent.com/926341/47960387-d7b1b100-dfc8-11e8-9b42-e6c5d99a8ee8.png)

I'be sending a PR considering the `rebase` strategy for you to review

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 950.0 AION (402.61 USD @ $0.42/AION) has been submitted by__:

 1. [@santteegt](https://gitcoin.co/profile/santteegt)



@kzeine please take a look at the submitted work:
* [PR](https://github.com/aionnetwork/aion/issues/661) by @santteegt

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aionnetwork/aion/661/1353)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/aionnetwork/aion/661/1353).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $51,563.98 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 950.0 AION (402.61 USD @ $0.42/AION)  attached to this issue has been approved & issued to @santteegt.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aionnetwork/aion/661/1353)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $53,616.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by santteegt** [comment]
Thank you. The token swap was successful. In case you need help with the stats log formatting, let me know. I'm happy to help.
